FROM postgres
MAINTAINER cablo
COPY ./postgres/create-db.sql /docker-entrypoint-initdb.d/create-db.sql

# TODO solve logging sql
#COPY postgresql.conf /usr/share/postgresql/postgresql.conf
#RUN chmod 644 /usr/share/postgresql/postgresql.conf
#RUN echo "cp /usr/share/postgresql/postgresql.conf /var/lib/postgresql/data/postgresql.conf" >> /docker-entrypoint-initdb.d/init-user-db.sh
