# used for debug against docker container only
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cablo
    username: cablo
    password: cablo
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    db-type: postgres

micronaut:
  application:
    name: knuspr
  router:
    static-resources:
      react:
        paths: classpath:public
        mapping: /public/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - "http://localhost:3000"

flyway:
  datasources:
    default:
      enabled: true
