apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: k8s-knuspr
          image: cablo/knuspr-postgres-image
          env:
            - name: POSTGRES_DB
              value: "cablo"
            - name: POSTGRES_USER
              value: "cablo"
            - name: POSTGRES_PASSWORD
              value: "cablo"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: knuspr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knuspr
  template:
    metadata:
      labels:
        app: knuspr
    spec:
      containers:
        - name: k8s-knuspr
          image: cablo/knuspr-app-image
          env:
            - name: DATASOURCES_DEFAULT_URL
              value: "jdbc:postgresql://postgres-service:5432/cablo"
            - name: DATASOURCES_DEFAULT_USERNAME
              value: "cablo"
            - name: DATASOURCES_DEFAULT_PASSWORD
              value: "cablo"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: knuspr-service
spec:
  type: NodePort
  selector:
    app: knuspr
  ports:
    - port: 8080
